apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayservice
  template:
    metadata:
      labels:
        app: gatewayservice
    spec:
      containers:
        - name: gatewayservice
          image: ninoverhaegh/gatewayservice:latest
          ports:
            - containerPort: 8079
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
