name: DeployCloud

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        az aks get-credentials --resource-group TwotterResources --name TwotterCluster
        kubectl apply -f https://raw.githubusercontent.com/Kibuns/GatewayService/master/deployment.yaml --force
